/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.view;

import bll.Perdoruesi;
import bll.Product;
import dal.PerdoruesiRepository;
import dal.PharmacyException;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public static Perdoruesi p = new Perdoruesi();
  
    public LoginForm() {
        initComponents();
        overlay.setBackground(new Color(0, 0, 0, 200));
        this.setOpacity(0.9f);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        passwordlbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        namelbl = new javax.swing.JLabel();
        passwordtxt = new javax.swing.JPasswordField();
        usertxt = new javax.swing.JTextField();
        logInButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        overlay = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(17, 21, 48));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordlbl.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        passwordlbl.setForeground(new java.awt.Color(18, 154, 134));
        passwordlbl.setText("Password");
        jPanel2.add(passwordlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 141, 30));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 360, 10));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 360, 10));

        namelbl.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        namelbl.setForeground(new java.awt.Color(18, 154, 134));
        namelbl.setText("Username ");
        jPanel2.add(namelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 141, 30));

        passwordtxt.setBackground(new java.awt.Color(17, 21, 48));
        passwordtxt.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        passwordtxt.setForeground(new java.awt.Color(240, 240, 240));
        passwordtxt.setBorder(null);
        passwordtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordtxtKeyTyped(evt);
            }
        });
        jPanel2.add(passwordtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 360, 30));

        usertxt.setBackground(new java.awt.Color(17, 21, 48));
        usertxt.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        usertxt.setForeground(new java.awt.Color(240, 240, 240));
        usertxt.setBorder(null);
        jPanel2.add(usertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 360, 30));

        logInButton.setBackground(new java.awt.Color(18, 154, 134));
        logInButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        logInButton.setText("Log In");
        logInButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButtonActionPerformed(evt);
            }
        });
        logInButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                logInButtonKeyTyped(evt);
            }
        });
        jPanel2.add(logInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 150, 50));

        cancelButton.setBackground(new java.awt.Color(18, 154, 134));
        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 150, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 560, 580));

        overlay.setBackground(new java.awt.Color(255, 255, 255));
        overlay.setForeground(new java.awt.Color(255, 255, 255));
        overlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mimoza\\Desktop\\LabCourse\\PharmacyManagementSystemSoftware\\images\\hygeia.png")); // NOI18N
        overlay.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 100, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mimoza\\Desktop\\LabCourse\\PharmacyManagementSystemSoftware\\images\\Pills-PNG-Transparent-Image.png")); // NOI18N
        overlay.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 630, 610));

        getContentPane().add(overlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(-152, -10, 720, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButtonActionPerformed
        // TODO add your handling code here:

        try {
            String username = usertxt.getText();
            String password = new String(passwordtxt.getPassword());
            PerdoruesiRepository pr = new PerdoruesiRepository();
            p = pr.loginByUsernameAndPassword(username, password);
            if (p != null){
                new MainForm(p.getRoleID().getRoleID(), p.getName() + " " + p.getLastName()).setVisible(true);
               
                this.dispose();
            }
        } catch (PharmacyException ex) {
            JOptionPane.showMessageDialog(this, "Incorrect !");
        }
    }//GEN-LAST:event_logInButtonActionPerformed

    private void logInButtonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_logInButtonKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_logInButtonKeyTyped

    private void passwordtxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordtxtKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if (enter == KeyEvent.VK_ENTER) {
            try {
                String username = usertxt.getText();
                String password = new String(passwordtxt.getPassword());
                PerdoruesiRepository pr = new PerdoruesiRepository();
                p = pr.loginByUsernameAndPassword(username, password);
                if (p != null) {
                    new MainForm(p.getRoleID().getRoleID(), p.getName() + " " + p.getLastName()).setVisible(true);
                    this.dispose();
                }
            } catch (PharmacyException ex) {
                JOptionPane.showMessageDialog(this, "Incorrect !");
            }
        }
    }//GEN-LAST:event_passwordtxtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton logInButton;
    private javax.swing.JLabel namelbl;
    private javax.swing.JPanel overlay;
    private javax.swing.JLabel passwordlbl;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JTextField usertxt;
    // End of variables declaration//GEN-END:variables
}
