/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.view;

import bll.Perdoruesi;
import bll.Role;
import dal.PharmacyException;
import dal.RoleInterface;
import dal.RoleRepository;
import dal.PerdoruesiInterface;
import dal.PerdoruesiRepository;
import gui.model.RoleTypeComboBoxModel;
import gui.model.PerdoruesiTableModel;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Adis Durguti
 */
public class PerdoruesiForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form PerdoruesiForm
     */
    public PerdoruesiForm() {
        initComponents();
        loadTable();
        loadComboBoxCategory();
        groupButton();
        tabelaSelectedIndexChange();
    }

    ButtonGroup bg = new ButtonGroup();

    PerdoruesiInterface pi = new PerdoruesiRepository();
    PerdoruesiTableModel ptm = new PerdoruesiTableModel();

    RoleInterface ri = new RoleRepository();
    RoleTypeComboBoxModel rtbm;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userIDtxt = new javax.swing.JTextField();
        userNametxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        lastNameTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        birthdayDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        passwordTxt = new javax.swing.JPasswordField();
        roleTypeComboBox = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        salaryTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        addUserBtn = new javax.swing.JButton();
        updateUserBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();

        setResizable(true);
        setTitle("User");

        userIDtxt.setEditable(false);

        userNametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userNametxtKeyReleased(evt);
            }
        });

        nameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTxtKeyReleased(evt);
            }
        });

        lastNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lastNameTxtKeyReleased(evt);
            }
        });

        jLabel1.setText("User ID");

        jLabel3.setText("UserName");

        jLabel4.setText("Password");

        jLabel5.setText("Name");

        jLabel6.setText("LastName");

        emailTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTxtFocusGained(evt);
            }
        });

        jLabel7.setText("Email");

        jLabel8.setText("Birthday");

        maleRadioButton.setText("Male");
        maleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioButtonActionPerformed(evt);
            }
        });

        femaleRadioButton.setText("Female");

        passwordTxt.setText("jPasswordField1");

        jLabel9.setText("RoleType");

        salaryTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                salaryTxtKeyReleased(evt);
            }
        });

        jLabel10.setText("Salary");

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(userTable);

        addUserBtn.setText("Add User");
        addUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserBtnActionPerformed(evt);
            }
        });

        updateUserBtn.setText("Update User");
        updateUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUserBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete User");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(240, 240, 240));

        jSeparator2.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator8)
                            .addComponent(userNametxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(birthdayDateChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userIDtxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roleTypeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salaryTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(maleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(femaleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(addUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(updateUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(55, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roleTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)
                        .addComponent(userNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(2, 2, 2)
                        .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(2, 2, 2)
                        .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(2, 2, 2)
                        .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(3, 3, 3)
                        .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(birthdayDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maleRadioButton)
                            .addComponent(femaleRadioButton))
                        .addGap(13, 13, 13)
                        .addComponent(jLabel10)
                        .addGap(3, 3, 3)
                        .addComponent(salaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void tabelaSelectedIndexChange() {
        final ListSelectionModel rowSM = userTable.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent Ise) {
                if (Ise.getValueIsAdjusting()) {
                    return;
                }
                ListSelectionModel rowSM = (ListSelectionModel) Ise.getSource();
                int selectedIndex = rowSM.getAnchorSelectionIndex();
                if (selectedIndex > -1) {
                    Perdoruesi u = ptm.getPerdoruesi(selectedIndex);
                    userIDtxt.setText(u.getPerdoruesiID() + "");
                    //roleIDtxt.setText(u.getRoleID() + "");
                    roleTypeComboBox.setSelectedItem(u.getRoleID());
                    roleTypeComboBox.repaint();
                    userNametxt.setText(u.getUserName() + "");
                    passwordTxt.setText(u.getPassword() + "");
                    nameTxt.setText(u.getName() + "");
                    lastNameTxt.setText(u.getLastName() + "");
                    emailTxt.setText(u.getEmail() + "");
                    birthdayDateChooser.setDate(u.getBirthDate());
                    if (u.getGender() == 'M') {
                        maleRadioButton.setSelected(true);
                    } else if (u.getGender() == 'F') {
                        femaleRadioButton.setSelected(true);
                    }
                    salaryTxt.setText(u.getSalary() + "");

                }
            }
        });
    }

    public void loadTable() {
        try {
            List<Perdoruesi> list = pi.findAll();
            ptm.addList(list);
            userTable.setModel(ptm);
            ptm.fireTableDataChanged();
        } catch (PharmacyException ex) {
            Logger.getLogger(PerdoruesiForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void loadComboBoxCategory() {
        try {
            List<Role> list = ri.findAll();
            rtbm = new RoleTypeComboBoxModel(list);
            roleTypeComboBox.setModel(rtbm);
            roleTypeComboBox.repaint();
        } catch (PharmacyException ce) {
            JOptionPane.showMessageDialog(this, ce.getMessage());
        }
    }

    void groupButton() {

        bg.add(maleRadioButton);
        bg.add(femaleRadioButton);
    }

    void clear() {
        userTable.clearSelection();
        userIDtxt.setText("");
        roleTypeComboBox.setSelectedItem(null);
        roleTypeComboBox.repaint();
        userNametxt.setText("");
        passwordTxt.setText("");
        nameTxt.setText("");
        lastNameTxt.setText("");
        emailTxt.setText("");
        birthdayDateChooser.setDate(null);
        bg.clearSelection();
        salaryTxt.setText("");
    }
    private void maleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioButtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_maleRadioButtonActionPerformed
    boolean check() {
        if (!(roleTypeComboBox.getSelectedIndex() == -1 || userNametxt.getText().trim().equals("") || passwordTxt.getText().trim().equals("")
                || nameTxt.getText().trim().equals("") || lastNameTxt.getText().trim().equals("") || emailTxt.getText().trim().equals("") || birthdayDateChooser.getDate().equals(null) || bg.getSelection() == null
                || salaryTxt.getText().trim().equals(""))) {
            return true;
        }
        return false;
    }
     public static boolean isValid(String email) 
    { 
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."+ 
                            "[a-zA-Z0-9_+&*-]+)*@" + 
                            "(?:[a-zA-Z0-9-]+\\.)+[a-z" + 
                            "A-Z]{2,7}$"; 
                              
        Pattern pat = Pattern.compile(emailRegex); 
        if (email == null) 
            return false; 
        return pat.matcher(email).matches(); 
    } 
    private void addUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserBtnActionPerformed
        // TODO add your handling code here:
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        s.format(d);
        Calendar cal = Calendar.getInstance();
        cal.add(Calendar.YEAR, -25);
        Date d1 = cal.getTime();
        Calendar cal1 = Calendar.getInstance();
        cal1.add(Calendar.YEAR, -65);
        Date dl1 = cal1.getTime();
        Perdoruesi u = new Perdoruesi();
        if (check()) {
            if (!(birthdayDateChooser.getDate().after(d))) {
                if ((birthdayDateChooser.getDate().after(dl1)) && (birthdayDateChooser.getDate().before(d1))) {
                    if (isValid(emailTxt.getText())) {
                        Perdoruesi p = new Perdoruesi();
                        try {
                            // p.setPerdoruesiID(Integer.parseInt(userIDtxt.getText()));
                            p.setRoleID((Role) roleTypeComboBox.getSelectedItem());
                            p.setUserName(userNametxt.getText());
                            p.setPassword(passwordTxt.getText());
                            p.setName(nameTxt.getText());
                            p.setLastName(lastNameTxt.getText());
                            p.setEmail(emailTxt.getText());
                            p.setBirthDate(birthdayDateChooser.getDate());
                            if (maleRadioButton.isSelected()) {
                                p.setGender('M');
                            } else if (femaleRadioButton.isSelected()) {
                                p.setGender('F');
                            }
                            BigDecimal salary = new BigDecimal(salaryTxt.getText());
                            p.setSalary(salary);

                            pi.create(p);
                            clear();
                        } catch (PharmacyException ex) {
                            Logger.getLogger(PerdoruesiForm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else {
                         JOptionPane.showMessageDialog(this, "Invalid Email Address !");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Age should be over 25 and under 65 !");
                }
            } else {
                JOptionPane.showMessageDialog(this, "BirthDate cannot be greater than the actual date!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please ,fill all the required information !");
        }
        loadTable();

    }//GEN-LAST:event_addUserBtnActionPerformed

    private void updateUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUserBtnActionPerformed
        // TODO add your handling code here:
        int row = userTable.getSelectedRow();
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        s.format(d);
        Calendar cal = Calendar.getInstance();
        cal.add(Calendar.YEAR, -20);
        Date d1 = cal.getTime();
        Calendar cal1 = Calendar.getInstance();
        cal1.add(Calendar.YEAR, -65);
        Date dl1 = cal1.getTime();
        if (row >= 0) {
            if (check()) {
                if (!(birthdayDateChooser.getDate().after(d))) {
                    if ((birthdayDateChooser.getDate().after(dl1)) && (birthdayDateChooser.getDate().before(d1))) {
                        if(isValid(emailTxt.getText())){
                        try {
                            Perdoruesi p = ptm.getPerdoruesi(row);
                            // p.setPerdoruesiID(Integer.parseInt(userIDtxt.getText()));
                            p.setRoleID((Role) roleTypeComboBox.getSelectedItem());
                            p.setUserName(userNametxt.getText());
                            p.setPassword(passwordTxt.getText());
                            p.setName(nameTxt.getText());
                            p.setLastName(lastNameTxt.getText());
                            p.setEmail(emailTxt.getText());
                            p.setBirthDate(birthdayDateChooser.getDate());
                            if (maleRadioButton.isSelected()) {
                                p.setGender('M');
                            } else if (femaleRadioButton.isSelected()) {
                                p.setGender('F');
                            }
                            BigDecimal salary = new BigDecimal(salaryTxt.getText());
                            p.setSalary(salary);
                            pi.edit(p);
                        } catch (PharmacyException ex) {
                            JOptionPane.showMessageDialog(this, "MSG: " + ex.getMessage());
                        }
                        loadTable();
                        clear();
                        }else{
                             JOptionPane.showMessageDialog(this, "Invalid Email Address !");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Age should be over 25 and under 65 !");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "BirthDate cannot be greater than the actual date!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please ,fill all the required information !");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please , choose what you want to update !");
        }
    }//GEN-LAST:event_updateUserBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int row = userTable.getSelectedRow();
        if (row != -1) {
            Object[] ob = {"Yes", "No"};
            int i = JOptionPane.showOptionDialog(this, "Are u sure you want to delete ?", "Deletion", JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE, null, ob, ob[1]);
            if (i == 0) {
                try {
                    Perdoruesi p = ptm.getPerdoruesi(row);
                    pi.delete(p);
                    clear();
                    loadTable();
                } catch (PharmacyException ex) {
                    JOptionPane.showMessageDialog(this, "MSG: " + ex.getMessage());
                }
            } else {
                clear();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please , choose what you want to delete !");
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void userNametxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNametxtKeyReleased
        // TODO add your handling code here:
        if (!userNametxt.getText().matches("^[a-zA-Z]*$")) {
            JOptionPane.showMessageDialog(this, "Username cannot contain numbers !");
            userNametxt.setText("");
        } else {

        }

    }//GEN-LAST:event_userNametxtKeyReleased

    private void emailTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTxtFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtFocusGained

    private void nameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTxtKeyReleased
        // TODO add your handling code here:
        if (!nameTxt.getText().matches("^[a-zA-Z]*$")) {
            JOptionPane.showMessageDialog(this, "Name cannot contain numbers !");
            nameTxt.setText("");
        } else {

        }
    }//GEN-LAST:event_nameTxtKeyReleased

    private void lastNameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNameTxtKeyReleased
        // TODO add your handling code here:
        if (!lastNameTxt.getText().matches("^[a-zA-Z]*$")) {
            JOptionPane.showMessageDialog(this, "LastName cannot contain numbers !");
            lastNameTxt.setText("");
        } else {

        }
    }//GEN-LAST:event_lastNameTxtKeyReleased

    private void salaryTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salaryTxtKeyReleased
        // TODO add your handling code here:
        if (!salaryTxt.getText().matches("^[\\d,.]+$")) {
            JOptionPane.showMessageDialog(this, "Salary cannot contain letters !");
            salaryTxt.setText("");
        } else {

        }
    }//GEN-LAST:event_salaryTxtKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserBtn;
    private com.toedter.calendar.JDateChooser birthdayDateChooser;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JComboBox roleTypeComboBox;
    private javax.swing.JTextField salaryTxt;
    private javax.swing.JButton updateUserBtn;
    private javax.swing.JTextField userIDtxt;
    private javax.swing.JTextField userNametxt;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
